src/diffusers/schedulers/scheduling_dpmsolver_multistep_oneflow.py
This reverts commit d462a7f84a6ae7aa6b1300d71e2359621c2889ec.
=> Revert "fix cmake"

src/diffusers/__init__.py, src/diffusers/pipelines/__init__.py, src/diffusers/pipelines/alt_diffusion/__init__.py, src/diffusers/pipelines/alt_diffusion/modeling_roberta_series_oneflow.py, src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_oneflow.py
用法：
```python
import oneflow as torch
from diffusers import OneFlowAltDiffusionPipeline as AltDiffusionPipeline
pipeline = AltDiffusionPipeline.from_pretrained("BAAI/AltDiffusion-m9")
pipeline = pipeline.to("cuda")
prompt = "Astronaut riding a horse on Mars."
with torch.autocast("cuda"):
images = pipeline(prompt).images
for i, image in enumerate(images):
image.save(f"{prompt}-of-{i}.png")
```
=> altdiffusion oneflow backend

src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_oneflow.py
=> altdiffusion_support_nn.graph

src/diffusers/models/vae_oneflow.py
=> fix dtype of vae output

src/diffusers/__init__.py, src/diffusers/pipeline_oneflow_utils.py, src/diffusers/pipelines/__init__.py, src/diffusers/pipelines/stable_diffusion/__init__.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy_oneflow.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_oneflow.py
```python
import PIL
import requests
from io import BytesIO
import oneflow as torch
from diffusers import OneFlowStableDiffusionInpaintPipeline as StableDiffusionInpaintPipeline
def download_image(url):
response = requests.get(url)
return PIL.Image.open(BytesIO(response.content)).convert("RGB")
img_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo.png"
mask_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo_mask.png"
init_image = download_image(img_url).resize((512, 512))
mask_image = download_image(mask_url).resize((512, 512))
pipe = StableDiffusionInpaintPipeline.from_pretrained(
"runwayml/stable-diffusion-inpainting", …
```
=> Dev support stable diffusion inpainting

src/diffusers/modeling_oneflow_utils.py, src/diffusers/oneflow_graph_compile_cache.py, src/diffusers/pipeline_oneflow_utils.py, src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion_oneflow.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_oneflow.py, src/diffusers/utils/__init__.py, tests/test_pipelines_oneflow_graph_load.py
本 PR 
- 依赖的 oneflow 分支： https://github.com/Oneflow-Inc/oneflow/pull/9754
- 测试sd pipe line 可以保存和加载 unet graph，以实现 graph 的离线编译、在线加载，缩短 sd 启动时间
=> Support offline compile

tests/test_pipelines_oneflow_graph_load.py
- add cpu mem cost
- refine cuda mem cost
=> refine cost cnt

src/diffusers/pipeline_oneflow_utils.py, src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img_oneflow.py, tests/test_pipelines_oneflow_img2img_graph_load.py
solve 
1. AttributeError: 'OneFlowStableDiffusionImg2ImgPipeline' object has no attribute 'graph_compile_cache'
2. TypeError: __call__ in /home/zhaodi/diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img_oneflow.py line 642 got an unexpected keyword argument `compile_vae`
#100
=> img2img graph load

README.md, examples/control_net_canny.py, examples/image_to_image.py, examples/text_to_image.py, examples/text_to_image_alt.py, examples/text_to_image_dpmsolver.py, examples/text_to_image_inpaint.py, examples/text_to_image_sd2.py, src/onediff/__init__.py, src/onediff/pipeline_stable_diffusion_controlnet_oneflow.py, src/onediff/pipeline_stable_diffusion_img2img_oneflow.py
还有一些问题需要讨论和确定
1.  为支持Control Net需要的升级：
- huggingface官方的 [diffusers 0.14.0](https://github.com/huggingface/diffusers/releases/tag/v0.14.0) 支持了Control Net pipeline。所以我们要支持的话也需要安装0.14.0版本的diffusers `python3 -m pip install "transformers>=4.26" "diffusers[torch]==0.14.0"`
- canny example 中为了检测Canny edge用到了 cv2，需要安装 `pip install opencv-contrib-python`
2.  可能还需要测试升级diffusers版本后对其他pipeline的影响
3.  第一次提PR不知还有什么步骤需要完善
- https://huggingface.co/docs/diffusers/v0.14.0/en/api/pipelines/stable_diffusion/controlnet
- https://github.com/huggingface/diffusers/pull/2407
=> add control net support

examples/unet_torch_interplay.py
* 增加了模型的输入选项
* 增加图像分辨率的精细选项
* 解决了由于更换模型导致text embedding维度不匹配的问题
* 用dataclass来存数据
=> add multi-model and text_dim

src/onediff/graph_utils.py
=> fix save graph path

src/onediff/graph_utils.py
=> fix graph time statisic

README.md, src/onediff/pipeline_alt_diffusion_oneflow.py, src/onediff/pipeline_stable_diffusion_img2img_oneflow.py, src/onediff/pipeline_stable_diffusion_inpaint_oneflow.py, src/onediff/pipeline_stable_diffusion_oneflow.py
* 适配diffusers 0.15.0的lora和textualinversion功能
=> add lora and textualinversion

src/onediff/infer_compiler/convert_torch_to_of/__init__.py, src/onediff/infer_compiler/convert_torch_to_of/custom_register.py, src/onediff/infer_compiler/convert_torch_to_of/mock_diffusers/__init__.py, src/onediff/infer_compiler/convert_torch_to_of/mock_diffusers/attention_processor_1f.py, src/onediff/infer_compiler/convert_torch_to_of/mock_diffusers_quant/__init__.py, src/onediff/infer_compiler/convert_torch_to_of/mock_diffusers_quant/quant_diffusion_pipeline.py, src/onediff/infer_compiler/convert_torch_to_of/register.py, src/onediff/infer_compiler/import_tools/__init__.py, src/onediff/infer_compiler/import_tools/printer.py, src/onediff/infer_compiler/with_oneflow_compile.py, tests/convert_torch_to_of/test_quant_diffusion_pipeline.py
export ONEDIFF_SUPPRESS_WARNINGS="0"  启用警告（默认消除警告）
=> Dev support oneflow diffusers int8

src/infer_compiler_registry/register_diffusers/__init__.py, src/infer_compiler_registry/register_diffusers/attention_processor_oflow.py
fix: https://github.com/Oneflow-Inc/diffusers/issues/299
=> Replace call with forward in LoRAAttnProcessor2_0

src/infer_compiler_registry/register_diffusers/__init__.py, src/onediff/infer_compiler/transform/builtin_transform.py, src/onediff/infer_compiler/transform/manager.py
Before: 
> Replace can't find proxy oneflow module for: mock_diffusers_oflow_1700656183281553960.models.unet_2d_condition.UNet2DConditionModel. 
After: 
> Replace can't find proxy oneflow module for: <class 'diffusers.models.unet_2d_condition.UNet2DConditionModel'>.
=> fix register error msg

onediff_comfy_nodes/infer_compiler_registry/register_comfy/__init__.py, onediff_comfy_nodes/infer_compiler_registry/register_comfy/linear.py, onediff_comfy_nodes/modules/onediff_controlnet.py
兼容最新 comfyui的改动。
https://github.com/comfyanonymous/ComfyUI/commit/77755ab8dbc74f3f231aa817590401d7969f96a4
=> Compatibility with the latest ComfyUI update (commit b454a67)

examples/experimental/text_to_image_sdxl_torch_compile.py, src/onediff/infer_compiler/transform/builtin_transform.py
Address this [todo](https://github.com/siliconflow/onediff/pull/458#discussion_r1436227401)
=> fix an op convertion error

examples/text_to_image_sdxl_save_load.py, src/onediff/infer_compiler/transform/builtin_transform.py, src/onediff/infer_compiler/with_oneflow_compile.py
Related: https://github.com/siliconflow/onediff/issues/452
=> Quick fix vae load

src/infer_compiler_registry/register_diffusers_enterprise_lite/__init__.py, src/onediff/infer_compiler/transform/custom_transform.py
集成， https://github.com/siliconflow/diffusers-enterprise-lite
用法：https://github.com/siliconflow/diffusers-enterprise-lite/blob/main/tools/text-to-image-deep-cache-sdxl-hpc-1f.py
=> integrated_diffusers_enterprise_lite

onediff_sd_webui_extensions/compile_ldm.py, onediff_sd_webui_extensions/compile_sgm.py
替换 SpatialTransformer 中的 rearrange/reshape 操作，以支持 vm run 下动态切换分辨率。
经过测试，切换分辨率的速度大大提高（只有非常短的一点时间间隔）。
=> sd-weibui supports switching resolutions in the runtime of vm run

onediff_comfy_nodes/infer_compiler_registry/register_comfy/__init__.py, onediff_comfy_nodes/infer_compiler_registry/register_comfy/vae_patch.py
https://github.com/comfyanonymous/ComfyUI/blob/b4e915e74560bd2c090f9b4ed6b73b0781b7050e/comfy/ldm/modules/diffusionmodules/model.py#L243 
修复vae  动态shape
=> fix vae use

README.md, README_ENTERPRISE.md, examples/text_to_image_deep_cache_sdxl_enterprise.py, examples/text_to_image_sdxl_enterprise.py, onediff_comfy_nodes/README.md, onediff_diffusers_extensions/README.md
Add documents, scripts and models for OneDiff Enterprise
=> Documents for OneDiff Enterprise

onediff_comfy_nodes/__init__.py, onediff_comfy_nodes/_nodes.py, onediff_comfy_nodes/modules/onediff_controlnet.py, tests/comfyui/workflows/sdxl-control-lora-speedup.json
来源：https://github.com/siliconflow/onediff/issues/551 
下图测试工作流
=> Fix ControlNet Usage

benchmarks/image_to_video.py, onediff_comfy_nodes/utils/onediff_quant_utils.py, src/infer_compiler_registry/register_onediff_quant/quant_diffusion_pipeline.py, src/onediff/infer_compiler/with_fx_graph.py, src/onediff/infer_compiler/with_oneflow_compile.py
Support YGemm. Requires: https://github.com/siliconflow/oneflow/pull/94
=> Support YGemm

examples/text_to_image_sdxl.py, src/infer_compiler_registry/register_diffusers/__init__.py, src/infer_compiler_registry/register_diffusers/resnet_oflow.py, src/infer_compiler_registry/register_diffusers/unet_2d_blocks_oflow.py, src/infer_compiler_registry/register_diffusers/unet_2d_condition_oflow.py
fix multi resolutions bug.  https://github.com/siliconflow/onediff/issues/527
=> fix_multi_resolutions_bug

.github/workflows/examples.yml
Reverts siliconflow/onediff#637
=> Revert "Run turbo in examples"

examples/text_to_image_deep_cache_sd.py, onediff_diffusers_extensions/onediffx/deep_cache/models/unet_2d_blocks.py, onediff_diffusers_extensions/onediffx/deep_cache/models/unet_2d_condition.py, onediff_diffusers_extensions/onediffx/deep_cache/models/unet_3d_blocks.py, onediff_diffusers_extensions/setup.py
=> fix diffusers>=0.26 compatibility for deepcache/onediffx

src/infer_compiler_registry/register_diffusers/__init__.py
compatible with diffisers 0.26
=> compatible_with_diffisers_0.26

onediff_comfy_nodes/utils/graph_path.py
=> add_comfyui_save_graph_dir_variable

onediff_comfy_nodes/README.md, onediff_comfy_nodes/workflows/ComfyUI_InstantID_OneDiff.md
> 需求来源： https://github.com/siliconflow/onediff/issues/682
=> Add OneDiff for InstantID ComfyUI

onediff_comfy_nodes/infer_compiler_registry/register_comfy/deep_cache_unet.py, onediff_comfy_nodes/infer_compiler_registry/register_comfy/openaimodel.py, onediff_comfy_nodes/infer_compiler_registry/register_comfy/util.py
=> Allow image_only_indicator to be None (comfy)

src/onediff/infer_compiler/transform/builtin_transform.py, src/onediff/infer_compiler/transform/patch_for_comfy.py
修复 https://github.com/comfyanonymous/ComfyUI/commit/db8b59ecff7be40377d17ea69487f442b469c536  更新导致ci错误。
报 'MODULE' 'ProxyModule' object 'model.time_embed.0' in nn.Graph has no attribute 'bias_function' 错误
原因：comfyui 往 class 上绑定属性， 转化后 oneflow 模型 没有得到 torch class绑定的属性
```python
class Demo:
A = "a"
def __init__(self) -> None:
self.a = 1
demo = Demo()
print(demo.__dict__) # {'a': 1}
```
=> fix ci error

onediff_diffusers_extensions/examples/experimental/text_to_image_sdxl_torch_compile.py, onediff_diffusers_extensions/examples/image_to_image.py, onediff_diffusers_extensions/examples/text_to_image.py, onediff_diffusers_extensions/examples/text_to_image_sdxl.py, onediff_diffusers_extensions/examples/text_to_image_sdxl_mp_load.py, onediff_diffusers_extensions/examples/text_to_image_sdxl_save_load.py, onediff_diffusers_extensions/examples/text_to_image_sdxl_turbo.py, onediff_diffusers_extensions/examples/unet_torch_interplay.py
Fix ci error: https://github.com/siliconflow/onediff/actions/runs/8370390910/job/22917680476
=> import torch first

onediff_comfy_nodes/README.md
=> Fixed minor error in README.md

onediff_diffusers_extensions/onediffx/lora/__init__.py, onediff_diffusers_extensions/onediffx/lora/lora.py, onediff_diffusers_extensions/tests/test_lora.py
diffusers related api: https://huggingface.co/docs/diffusers/v0.27.2/en/api/loaders/lora#diffusers.loaders.LoraLoaderMixin.get_active_adapters
=> onediffx add get_active_adapters, and related unittest

benchmarks/image_to_video.py
=> Refine SVD diffusers example for graph save/load

onediff_diffusers_extensions/examples/text_to_image_deep_cache_sd_sdxl_enterprise.py, onediff_diffusers_extensions/examples/text_to_image_sd_enterprise.py, onediff_diffusers_extensions/examples/text_to_image_sdxl_enterprise.py
=> [Fix] diffusers enterprise example seed

onediff_comfy_nodes/__init__.py, onediff_comfy_nodes/_nodes.py, onediff_comfy_nodes/modules/nexfort/booster_basic.py, onediff_comfy_nodes/modules/oneflow/infer_compiler_registry/register_comfy/CrossAttentionPatch.py, onediff_comfy_nodes/modules/oneflow/infer_compiler_registry/register_comfy/CrossAttntionStateDictPatch.py, src/onediff/infer_compiler/oneflow/deployable_module.py, src/onediff/infer_compiler/oneflow/graph.py, src/onediff/infer_compiler/utils/graph_management_utils.py
下图测试工作流 为测试 支持 ComfyUI_IPAdapter_plus 切换checkpoint缓存，工作流。
=> Fix IPAdapter save load graph

.github/workflows/examples.yml, onediff_diffusers_extensions/examples/text_to_image.py, onediff_diffusers_extensions/examples/text_to_image_deep_cache_sd.py, onediff_diffusers_extensions/examples/text_to_image_deep_cache_sd_sdxl_enterprise.py, onediff_diffusers_extensions/examples/text_to_image_lcm.py, onediff_diffusers_extensions/examples/text_to_image_lcm_lora_sdxl.py, onediff_diffusers_extensions/examples/text_to_image_online_quant.py, onediff_diffusers_extensions/examples/text_to_image_sd_enterprise.py, onediff_diffusers_extensions/examples/text_to_image_sdxl_enterprise.py, onediff_diffusers_extensions/examples/text_to_image_sdxl_reuse_pipe.py, onediff_diffusers_extensions/examples/text_to_image_sdxl_turbo.py, tests/test_quantitative_quality.py
=> Refine manual seed

onediff_comfy_nodes/modules/oneflow/booster_basic.py, onediff_comfy_nodes/modules/oneflow/hijack_ipadapter_plus/set_model_patch_replace.py
=> Fix ipa weight update

.github/workflows/examples.yml, onediff_comfy_nodes/extras_nodes/nodes_compare.py, tests/comfy-docker-compose.yml, tests/comfyui/extra_model_paths.yaml, tests/comfyui/test_by_ui.py, tests/comfyui/workflows/sdxl-unet-speedup-graph-saver.json
fix https://github.com/siliconflow/sd-team/issues/353
=> Fix Ci Test

src/onediff/infer_compiler/backends/nexfort/README.md
https://github.com/siliconflow/nexfort/issues/87
=> Modify mode for dynamic shape in README

onediff_diffusers_extensions/examples/sd3/README.md
=> Update SD3 performance

.github/ISSUE_TEMPLATE/documentation.yml
borrowed from pytorch: https://github.com/pytorch/pytorch/tree/main/.github/ISSUE_TEMPLATE
=> add template for issue

.github/workflows/pub.yml
Fix: https://github.com/siliconflow/onediff/actions/runs/10127912851/job/28006236089
Ref: https://github.com/tskit-dev/tskit-site/issues/22#issuecomment-769163370
=> fix git shallow copy

README.md
reference: https://github.com/triton-lang/triton?tab=readme-ov-file#triton:~:text=MIT%20license-,We%27re%20hiring!,-If%20you%20are
=> add hiring in README.md
