siliconflow/onediff

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_oneflow.py
Reverts Oneflow-Inc/diffusers#60
> Juncheng Liu
> 用nsys profile 发现，加上 low._oneflow_internal.eager.Sync() 后，网络中两个unet之间的空隙变大了
> 
> Jianhao Zhang
> 进度条正常应该是因为有其它操作隐式触发了同步，当初进度条出问题的 diffuser commit 距离现在比较远了，在现在的 commit 上显式同步是作为一种保险。
> 看来这里是个两难的问题 :very_tired:
> 
> Juncheng Liu
> 我测试 stable diffusion v1.5 2.0 2.1 taiyi-chinese 4个模型，不加这个sync，进度条不会飞
> 
> Jianhao Zhang
> :rolling_on_the_floor_laughing: 那我来去掉吧
> 
> Jianhao Zhang
> 后续观察到问题了再开发新功能
> Revert "sync vm to get correct profiling result"

- src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_oneflow.py
基于27测试50step耗时：
| framwork | 50step耗时(s)| 
| -- | -- |
| torch@1.12.1+cu113 | 3| 
| oneflow(Eager) commit:https://github.com/Oneflow-Inc/oneflow/commit/7de22e9869ded4699a996d8ff32de56478461a00 | 2 | 
| oneflow(Graph)commit:https://github.com/Oneflow-Inc/oneflow/commit/7de22e9869ded4699a996d8ff32de56478461a00 | 1 |
> Stable diffusion inpainting support nn.graph

- examples/text_to_image_inpaint.py
- examples/text_to_image_sd2.py
- src/onediff/__init__.py
- src/onediff/pipeline_stable_diffusion_inpaint_oneflow.py
> Mock torch support stable diffusion inpaint pipeline

- src/onediff/infer_compiler/with_fx_graph.py
examples/torch_interpretor.py from 31.63it/s to 37.74it/s.
> Fix fx warning ONEFLOW_MLIR_ENABLE_INFERENCE_OPTIMIZATION

- src/onediff/infer_compiler/convert_torch_to_of/register.py
```python
1.   # Compile PyTorch model to OneFlow
2.     device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
3.     pytorch_model = PyTorchModel()
4.     of_model = oneflow_compile(pytorch_model, use_graph=True)
5. 
6. 
7.     # Verify conversion
8.     x = torch.randn(4, 4).to(device)
9.     pytorch_model.to(device)
10. 
11.     of_model.to(device)
```
代码第 11 行 ，如果 device 是 字符串 “cuda:0“是正常的，如果是 “torch.device" 缺少转换接口到导致  raise ValueError(f"Unsupported parameters in module.to: {arg}")
> [Fix]  compiled OneFlow model for CUDA execution.

- examples/requirements.txt
opencv-python==4.8.0.76 版本有问题，会报错
```text
AttributeError: module 'cv2.dnn' has no attribute 'DictValue'
```
https://github.com/opencv/opencv-python/issues/884#issuecomment-1684691124
> downgrading the opencv2

- src/onediff/infer_compiler/convert_torch_to_of/mock_diffusers/attention_processor_1f.py
diffusers的行为是，只要pytorch支持fuse attention kernel(判断nn.functional中是否有scaled_dot_product_attention借口)，或则开启use_attention_xformers，就直接忽略了upcast参数，直接执行half计算。因此OneDiff 忽略upcast无需打印warning
> rm_ignore_upcast_arg_warning

- examples/text_to_image_lcm_lora_sdxl.py
所有脚本运行在 3090 RTX 上
命令：
```bash
python diffusers/examples/text_to_image_sdxl.py --base /share_nfs/hf_models/stable-diffusion-xl-base-1.0 --prompt "Self-portrait oil painting, a beautiful cyborg with golden hair, 8k" --warmup 1 --seed 1 --n_steps 20 --height 1024 --width 1024 --compile False
```
命令：
```bash
python diffusers/examples/text_to_image_lcm_lora_sdxl.py --model_id /share_nfs/hf_models/stable-diffusion-xl-base-1.0 --prompt "Self-portrait oil painting, a beautiful cyborg with golden hair, 8k" --warmup 1 --seed 1 --steps 4 --height 1024 --width 1024 --disable
```
即使把 steps 调大，也不会有原始 sdxl 那样精致的效果：
```bash
python diffusers/examples/text_to_image_lcm_lora_sdxl.py --model_id /share_nfs/hf_models/stable-diffusion-xl-base-1.0 --prompt "Self-portrait oil painting, a beautiful cyborg with …
```
> add lcm lora sdxl example

- examples/text_to_image_lcm_lora_sdxl.py
增加 `mlir_enable_inference_optimization` 选项，默认不打开，确保图的质量与加速前一致。
```bash
script="diffusers/examples/text_to_image_lcm_lora_sdxl.py"
myprompt="Self-portrait oil painting, a beautiful cyborg with golden hair, 8k"
modelid="/share_nfs/hf_models/stable-diffusion-xl-base-1.0"
adapterid="/share_nfs/hf_models/lcm-lora-sdxl"
python $script \
--model_id  $modelid \
--adapter_id $adapterid \
--warmup 1 --disable --steps 4 --seed 1 \
--prompt "Self-portrait oil painting, a beautiful cyborg with golden hair, 8k" \
--width 1024 --height 1024 --output ptorch.png
python $script \
--model_id  $modelid \
--adapter_id $adapterid \
--warmup 1 --steps 4 --seed 1 \
--mlir_enable_inference_optimization \
--prompt "Self-portrait oil painting, a beautiful cyborg with golden hair, 8k" \
--width 1024 --height 1024 …
```
> Lcm lora add mlir flag

- src/onediff/infer_compiler/transform/builtin_transform.py
fix:
Only Tensors of floating point and complex dtype can require gradients
> fix-gradient-issue-with-non-floating-point-tensors

- examples/text_to_image_sdxl_turbo.py
```
python examples/text_to_image_sdxl_turbo.py
```
- 4 steps
- base(torch) : 0.402s
- compiled unet and vae: 0.247s (**+62.7% throughput**) 
- 1 step
- base(torch) : 0.216s
- compiled unet and vae: 0.163s (**+32.5% throughput**) 
- 4 steps
- base(torch) : 16.07it/s
- compiled unet and vae: 37.54 it/s (**+133.6% throughput**) 
- 1 step
- base(torch) : 15.34it/s
- compiled unet and vae: 40.41 it/s (**+163.4% throughput**) 
- NVIDIA GeForce RTX 3090
- diffusers version: 0.19.3
**Depending on the new oneflow community edition**:
cuda 11.8: `python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu118`
cuda12.1: `python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu121`
cuda12.2: `python3 …
> Add_sdxl_turbo_support

- .github/workflows/examples.yml
- examples/text_to_image_sdxl.py
- src/infer_compiler_registry/register_diffusers/attention_processor_oflow.py
Run:
```
export ONEFLOW_RUN_GRAPH_BY_VM="1"
python examples/text_to_image_sdxl.py --base=/share_nfs/hf_models/stable-diffusion-xl-base-1.0
```
修改 text_to_image_sdxl.py 脚本支持测试多分辨率：
```
if args.compile:
print("unet is compiled to oneflow.")
rewrite_self_attention(base.unet)
base.unet = oneflow_compile(base.unet)
base.vae = oneflow_compile(base.vae)
resolutions = [(1024, 1024), (512, 512), (768, 768), (1024, 512)]
for resolution in resolutions:
for i in range(args.warmup):
image = base(
prompt=args.prompt,
height=resolution[0],
width=resolution[1],
num_inference_steps=args.n_steps,
output_type=output_type,
).images
```
检查了 transformer_2d_oflow.py 已经支持了动态 shape，但是 attention_processor_oflow.py 中有些地方没有处理，这个 PR fixed。
Output:
****
上面是 slicon 的，community 待测试。
> Fix vae dynamic shape & CI

- src/onediff/infer_compiler/import_tools/mock_torch_context.py
```python
CUDA_VISIBLE_DEVICES=6 ONEDIFF_DEBUG=1 python examples/text_to_image_controlnet.py \
--controlnet  /share_nfs/hf_models/sd-controlnet-canny \
--base /share_nfs/hf_models/stable-diffusion-v1-5/ --input_image input_image_vermeer.png 
```
<details>
<summary> Output </summary>
```shell
(dev_comfy) fengwen@oneflow-28:~/packages/diffusers$ CUDA_VISIBLE_DEVICES=6 ONEDIFF_DEBUG=1 python examples/text_to_image_controlnet.py --controlnet  /share_nfs/hf_models/sd-controlnet-canny  --base /share_nfs/hf_models/stable-diffusion-v1-5/ --input_image input_image_vermeer.png 
Loading pipeline components...:   0%|                                      | 0/7 [00:00<?, ?it/s]`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be …
```
> fix_oneflow_mock

- examples/image_to_image_controlnet.py
Performance:
|                           | torch | +compiled unet | +compiled controlnet | +compiled vae | compiled total speedup |
|---------------------------|-------|----------------|----------------------|---------------|------------------------|
| Denoising loop (iter/s)   | 15.76 | 23.5           | 27.05                | 27.03         | 171.5%                 |
| End2End pipeline (iter/s) | 1.64  | 1.95           | 2.9                  | 3.50          | 213%                   |
| End2End pipeline (s)      | 0.595 | 0.507          | 0.354                | 0.284         | 210%                   |
- StableDiffusionControlNetImg2ImgPipeline
- device: RTX 3090
- width * hight: 512*512
- steps: 7(Denoising step is 5)
Run:
```
python examples/image_to_image_controlnet.py --compile_unet …
```
> add image to image vae compile demo

- onediff_sd_webui_extensions/README.md
- onediff_sd_webui_extensions/scripts/onediff.py
* 增加 sd-webui 性能数据
* 修复刚启动时设置 compiled model 的问题。这本是为 refiner model 引入的逻辑，但是刚启动时不应该这么设置，否则会影响 torch 的推理。可以判断 `_compiled` 不为 None 时设置。但是引入 refiner model 每次都会重新编译两个模型，所以暂时删除这个逻辑。
> add sd-webui performance data; fix refiner model bug

- benchmarks/README.md
- benchmarks/docker/config/community-default.yaml
- benchmarks/docker/main.py
模型下载，由 ossutil （需要登录，不方便），改成 zip 下载所有，直接解压使用。
> add oss model url

- src/onediff/infer_compiler/__init__.py
- src/onediff/infer_compiler/transform/__init__.py
- src/onediff/infer_compiler/transform/builtin_transform.py
- src/onediff/infer_compiler/with_fx_graph.py
- src/onediff/infer_compiler/with_fx_interpreter.py
修复了--compile_with_dynamo flag下oneflow无法支持PyTorch 2.1的bug
bug复现如下
```
python ~/onediff2/examples/experimental/text_to_image_sdxl_torch_compile.py --compile=false --compile_with_dynamo --base=/share_nfs/hf_models/stable-diffusion-xl-base-1.0
```
bug触发位置
```Python
if cmd_args.compile_with_dynamo:
print("unet is compiled to oneflow with torch.compile.")
from onediff.infer_compiler import oneflow_backend
base.unet = torch.compile(
base.unet, fullgraph=True, mode="reduce-overhead", backend=oneflow_backend
)
```
> support mode parameter in  PyTorch 2.1

- README.md
- benchmarks/docker/config/community-default.yaml
- onediff_comfy_nodes/README.md
- onediff_sd_webui_extensions/README.md
- onediff_sd_webui_extensions/install.py
- onediff_sd_webui_extensions/scripts/onediff.py
- setup.py
主要修改
* 用 fused_multi_head_attention_inference_v2 完成 CrossAttention 的核心计算。UNetModel 从 4.49it/s 提升到 6.71it/s。
* 更新 readme 中的性能数据，base 由 torch 改为 TensorRT。
* time_embed 的替换会触发 mock，最新的 onediff 需要将 sgm 包路径添加到 sys.path，否则会报 import 错误。（已经跟冯文确认过）
* 将 sd-webui 和 comfyUI readme 中 onediff 的 git 地址由 oneflow 改为 siliconflow。
* 修复 sd-webui 安装说明中两个命令的顺序。
> use fused_multi_head_attention_inference_v2 to implement CrossAttention

- README.md
- onediff_comfy_nodes/__init__.py
- onediff_comfy_nodes/_nodes.py
- onediff_comfy_nodes/utils/model_patcher.py
- src/onediff/infer_compiler/with_oneflow_compile.py
使用 OneDiffCheckpointLoader 避免用户 手动指定使用保存的 graph。
如下图避免用户使用 画红框的节点 ，引发不必要的麻烦。
> Add OneDiffCheckpointLoader

- src/infer_compiler_registry/register_diffusers/__init__.py
- src/infer_compiler_registry/register_diffusers/transformer_spatial_oflow.py
This PR is done：
打开 ONEFLOW_RUN_GRAPH_BY_VM 的情况下，编译 SVD 的 VAE。在**一次推理**中，diffusers 会有一些 reshape op 涉及到动态维度，导致第一次执行 VAE 挂掉，这个 PR 处理了下。
> Fix SVD VAE compile for diffuser

- onediff_sd_webui_extensions/compile_ldm.py
- onediff_sd_webui_extensions/compile_sgm.py
- onediff_sd_webui_extensions/compiled_model.py
- onediff_sd_webui_extensions/install.py
- onediff_sd_webui_extensions/scripts/onediff.py
- onediff_sd_webui_extensions/sd_webui_onediff_utils.py
主要改动
* 修复 [issue: webui 切换模型会报错](https://github.com/siliconflow/onediff/issues/435)。v1-5-pruned 模型对应的代码是 lgm 下的 UNetModel，原先并不支持其编译。
* 重构代码，将编译相关的代码从 Script 中拆出来。
* sd-webui 在加载插件时，将对应 extension（而不是 scripts） 的目录放到 sys.path。现在可以将代码拆开了。
* 因为 ldm、sgm、script 都需要访问 model，而 model 只能作为全局变量，所以只能放到一个单独的文件中。
* 将 ldm、sgm 的 unet 编译分别放到单独的文件。
> support v1-5-pruned model in sd-webui

- README.md
- src/onediff/infer_compiler/with_oneflow_compile.py
- tests/test_compiled_model_submodule.py
之前直接赋值 `self.xxx = some_nn_Module` 的写法，会在 `self._modules 中写入一个 key='xxx'` 的键值对，这是由于 torch.nn.Module 的 `__setattr__` 决定的，导致遍历、取 state_dict 等行为得到的结果与期望值不符，会多一层不必要的 _torch_module 或者 _deployable_module_model，比如下列场景：
```python3
In [1]: from onediff.infer_compiler import oneflow_compile
In [2]: from torchvision.models.resnet import resnet50
In [3]: model = resnet50(pretrained=False, progress=True).eval()
In [4]: of_model = oneflow_compile(model, use_graph=True)
In [5]: of_model._modules.keys()
Out[5]: odict_keys(['_deployable_module_model'])
In [6]: of_model._deployable_module_model._modules.keys()
Out[6]: odict_keys(['_torch_module']) …
```
> use object.__setattr__ in DualModule and DeployableModule to avoid unexpected key in self._modules

- onediff_comfy_nodes/_nodes.py
> Fix SVD Speedup overflow

- benchmarks/image_to_video.py
- src/infer_compiler_registry/register_diffusers/__init__.py
- src/infer_compiler_registry/register_diffusers/spatio_temporal_oflow.py
This PR is done:
issue: https://github.com/siliconflow/sd-team/issues/240
Run:
```
export ONEFLOW_RUN_GRAPH_BY_VM="1"
python3 examples/image_to_video.py --variant fp16 --output-video vm.mp4 --decode-chunk-size 4 --run_multiple_resolutions true
```
Output:
```
Loading pipeline components...: 100%|█████████████████████████████████████████████████████| 5/5 [00:00<00:00,  7.50it/s]
warmup:
100%|███████████████████████████████████████████████████████████████████████████████████| 25/25 [02:29<00:00,  5.99s/it]
infer:
100%|███████████████████████████████████████████████████████████████████████████████████| 25/25 [00:28<00:00,  1.15s/it]
test dynamic resolution switch:
100%|███████████████████████████████████████████████████████████████████████████████████| 25/25 [00:28<00:00,  1.15s/it]
```
> Support SVD dynamic shape[feat]

- onediff_diffusers_extensions/diffusers_extensions/utils/__init__.py
it errors out when importing it right now:
```
2024-01-26 16:33:14.814 [stderr   ]   File "/home/cicero/projects/serverless-registry/registry/image/fast_sdxl/inference.py", line 176, in enable_loras
2024-01-26 16:33:14.814 [stderr   ] ModuleNotFoundError: No module named 'diffusers_extensions.utils'
```
> make diffusers_extensions.utils a package

- examples/image_to_image_controlnet.py
```shell 
python image_to_image_controlnet.py \
--base /share_nfs/hf_models/sd-turbo/  \
--controlnet /share_nfs/hf_models/controlnet-sd21-canny-diffusers  \
--input_image /share_nfs/hf_models/input_image_vermeer.png \
--quant_unet 0 \
--warmup 1 \
--height 512 \
--width 512 \
--saved_image cmd_1.png 
python image_to_image_controlnet.py \
--base /share_nfs/hf_models/sd-turbo/  \
--controlnet /share_nfs/hf_models/controlnet-sd21-canny-diffusers  \
--input_image /share_nfs/hf_models/input_image_vermeer.png \
--quant_unet 1 \
--warmup 1 \
--height 512 \
--width 512 \
--saved_image cmd_2_quant.png 
```
|  | GPU MEM |
| --- | --- |
|cmd 1 |6680MiB MiB|
| cmd 2 |6164MiB MiB|
- Quantized conv: 66 
- Quantized linear: 216 
- oneflow: version: 0.9.1.dev20240129+cu121 git_commit: 6458a12 …
> add quant_unet

- examples/text_to_image_sdxl.py
- src/onediff/infer_compiler/with_oneflow_compile.py
background: https://github.com/siliconflow/sd-team/issues/191#issue-2063207008
test code:
```python
import oneflow as flow
from onediff.infer_compiler.with_oneflow_compile import oneflow_compile
from onediff.infer_compiler.transform import register
import torch
class Modulelist(torch.nn.Module):
def __init__(self):
super().__init__()
self.module_list = torch.nn.Sequential(
*[torch.nn.Linear(4, 4, bias=None) for _ in range(5)]
)
def forward(self, x):
return self.module_list(x)
class OfModulelist(flow.nn.Module):
def __init__(self):
super().__init__()
self.module_list = flow.nn.Sequential(
*[flow.nn.Linear(4, 4, bias=None) for _ in range(5)]
)
def forward(self, x):
return self.module_list(x)
register(torch2oflow_class_map={Modulelist: OfModulelist})
model = Modulelist()
of_model = …
```
> Refactor dualmodule._modules

- src/onediff/infer_compiler/with_oneflow_compile.py
对于一些 module，经过 oneflow_compile 之后，丢失了 `__dict__` 中的信息。
比如 Conv2d，变成 MixedDualModule 之后，in_channels 实际上存到了 `MixedDualModule._torch_module.__dict__` 里面了。而 `MixedDualModule.extra_repr` 会在当前的 `__dict__` 里面找 in_channels 这些参数，当然找不到，从而 print 时候报错，很影响 debug。
这个 PR 把 DualModule 的 extra_repr 定向到了 torch module，这样就可以找到了。
另外在 repr 返回类名的时候，把被编译的类名也加了进去，能知道是什么 module 被编译了。
修改前后对比如下所示：
before:
```python
In [1]: import torch
In [2]: from onediff.infer_compiler.with_oneflow_compile import oneflow_compile
In [3]: c = torch.nn.Conv2d(3, 3, 3)
In [4]: oneflow_compile(c)
Out[4]: ---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/miniconda3/envs/py10/lib/python3.10/site-packages/IPython/core/formatters.py: …
```
> add repr of dualmodule

- examples/text_to_image_sdxl.py
- onediff_comfy_nodes/infer_compiler_registry/register_comfy/__init__.py
- onediff_comfy_nodes/infer_compiler_registry/register_comfy/attention.py
- onediff_comfy_nodes/infer_compiler_registry/register_comfy/openaimodel.py
- onediff_comfy_nodes/infer_compiler_registry/register_comfy/util.py
> [feat] SVD dynamic shape for comfyui

- benchmarks/instant_id.py
- benchmarks/text_to_image.py
onediff自带的EulerDiscreteScheduler存在不必要的cuda synchronize开销，且生成图像质量较低，换为EulerAncestralDiscreteScheduler后跑SDXL和instant id有2%的加速效果，且生成图像质量较高。加速效果已在4090和A100上验证
> use EulerAncestralDiscreteScheduler for instant_id and text_to_image

- src/onediff/infer_compiler/utils/args_tree_util.py
- src/onediff/infer_compiler/with_oneflow_compile.py
来源：https://github.com/siliconflow/onediff/pull/619#issuecomment-1926076515
> Fix duplicate compilation

- src/onediff/infer_compiler/import_tools/importer.py
- src/onediff/infer_compiler/transform/builtin_transform.py
测试：
```shell
from onediff.infer_compiler.transform import torch2oflow
import torch 
mod = torch.nn.Linear 
of_mod = torch2oflow(mod)
print(of_mod) # <class 'oneflow.nn.modules.linear.Linear'>
x = 9 
print(f'{isinstance(x, type)=}') # isinstance(x, type)=False
```
> Supporting obj is not an object.

- onediff_diffusers_extensions/setup.py
- src/infer_compiler_registry/register_diffusers/__init__.py
- src/onediff/infer_compiler/transform/builtin_transform.py
- src/onediff/infer_compiler/transform/custom_transform.py
- src/onediff/infer_compiler/transform/manager.py
- src/onediff/infer_compiler/utils/log_utils.py
- Fix converter warning for LoraCompatibleLinear.
- Fix import error for diffusers==0.26.1 which causes patch failure.
- Change default log level to warning to make mistakes more noticeable.
- Check if libs are available before apply patches.
> fix compatibility with peft and diffusers 0.26.1

- onediff_diffusers_extensions/setup.py
Run CI with diffusers 0.26.2
Related: https://github.com/siliconflow/onediff/issues/642
> Update diffusers version to latested

- onediff_diffusers_extensions/examples/image_to_image.py
- src/infer_compiler_registry/register_diffusers/attention_processor_oflow.py
- src/onediff/optimization/attention_processor.py
> [Fix] black images issues with diffusers SD2.1

- src/infer_compiler_registry/register_diffusers/__init__.py
- src/infer_compiler_registry/register_diffusers/spatio_temporal_oflow.py
fix svd multi resolution error in https://github.com/siliconflow/onediff/issues/753
> fix_multi_resulotion_error

- onediff_comfy_nodes/utils/model_patcher.py
fix: https://github.com/siliconflow/onediff/issues/772
> Fix AttributeError in OneFlowDeepCacheSpeedUpModelPatcher

- onediff_sd_webui_extensions/onediff_hijack.py
存在的问题：在 sd-webui 中，onediff 仅支持 64 倍分辨率的图片，对应的 issue 是 https://github.com/siliconflow/onediff/issues/832 （本质原因是，非 64 倍分辨率时，unet 上下采样所产生的张量维度误差会导致 `cat` 操作失败）。
解决方法：发现 sd-webui 是通过劫持 `torch.cat` 来应对这一问题以支持 8 倍分辨率的，所以对应地，只需要在 onediff 中对 `oneflow.cat` 进行劫持即可。
> Support 8x resolution by hijacking cat in webui

- onediff_comfy_nodes/extras_nodes/nodes_compare.py
- src/onediff/infer_compiler/utils/param_utils.py
The python versions supported by onediff are 3.8~3.11, while `removeprefix` was introduced in 3.9.
> fix removeprefix for python 3.8

- tests/convert_torch_to_of/test_torch2of_demo.py
1. `get_mock_cls_name` 在目前版本里是不存在的方法。
2. 改为单元测试。
> Fix bug for torch2oflow demo test

- onediff_diffusers_extensions/onediffx/lora/lora.py
- onediff_diffusers_extensions/onediffx/lora/utils.py
LoRA 加载有如下参数：
1. B 矩阵 (m x r) 和 A 矩阵 (r x n)，也就是 lora_down 和 lora_up
2. alpha 用来控制 LoRA 在模型中的权重
3. rank 也就是 1. 中的 r
计算是 weight += B@A * alpha / rank * lora_scale。如果 LoRA 中没有 alpha 这个参数，那么计算就变成 weight += B@A * scale。
bug：之前为了节省计算量，把A * alpha / rank * scale 直接保存成了 A，对于 scale=0 的输入，A 就变成了全 0 的矩阵
我看了 peft 里面和 lora_alpha 有关的计算，这里都没有判断是否为 None，说明 lora_alpha 传到这里都是有值的
然后又看了 diffusers 调用 peft 的部分，这里设定了 lora_alpha 默认和 r 相等
https://github.com/huggingface/diffusers/blob/main/src/diffusers/utils/peft_utils.py#L150-L153
所以修复方式是 A 不使用这种耍小聪明的方式保存，而是保存原来的矩阵，把标量乘法的融合放在 alpha / rank * lora_scale 这里做
> [fix bug] OneDiffX `load_and_fuse_lora` when `lora_scale == 0` makes w_up to allzeros

- onediff_comfy_nodes/benchmarks/resources/workflows/baseline/txt2img.json
- onediff_comfy_nodes/benchmarks/resources/workflows/oneflow/txt2img.json
- onediff_comfy_nodes/benchmarks/scripts/run_oneflow_case_ci.sh
- onediff_comfy_nodes/benchmarks/scripts/text_to_image.py
- onediff_comfy_nodes/benchmarks/src/input_registration.py
- onediff_comfy_nodes/modules/booster_cache.py
- onediff_comfy_nodes/modules/oneflow/booster_basic.py
- onediff_comfy_nodes/modules/oneflow/hijack_utils.py
- src/onediff/infer_compiler/backends/oneflow/deployable_module.py
- src/onediff/infer_compiler/backends/oneflow/param_utils.py
- tests/comfy-docker-compose.yml
修复： https://github.com/siliconflow/sd-team/issues/423
> Auto-Sync Graph Tensor on Weight Update

- onediff_comfy_nodes/modules/oneflow/hijack_animatediff/motion_module_ad.py
In order to support ComfyUI-AnimateDiff-Evolved（1b660e535381a4b4e4028aad38b7ae21c81b861c）
> to_support_animatediff

- onediff_comfy_nodes/modules/booster_cache.py
`NameError: name 'is_oneflow_available' is not defined`
```
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
loaded straight to GPU
Requested to load SDXL
Loading 1 new model
Cache lookup: Key='2a7f8ef5-49f3-4eba-b608-ae7acbb2e7c6', Cached Model Type='<class 'comfy.model_base.SDXL'>'
Cache lookup: Key='1bc2cd79-33f5-45fe-9421-46d892f695f6', Cached Model Type='<class 'NoneType'>'
!!! Exception during processing !!!
Traceback (most recent call last):
File "/app/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/app/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, …
```
> [minor-fix] Update booster_cache.py to import utility

- src/infer_compiler_registry/register_diffusers/transformer_2d/v_0_28.py
- src/infer_compiler_registry/register_diffusers/transformer_2d_oflow.py
- src/infer_compiler_registry/register_diffusers/unet_2d_blocks_oflow.py
- src/infer_compiler_registry/register_diffusers/unet_2d_condition_oflow.py
- src/onediff/infer_compiler/backends/oneflow/args_tree_util.py
- src/onediff/infer_compiler/backends/oneflow/import_tools/patch_for_compiler.py
- src/onediff/infer_compiler/backends/oneflow/online_quantization_utils.py
社区用户反馈 0.29 diffusers 切换分辨率报错 https://github.com/siliconflow/onediff/issues/1033
原因是 0.29 的 transformer2d 的实现从 diffusers.models.transformer_2d 挪到了 diffusers.models.transformers.transformer_2d 里面，导致原来的代码 register 转换的 map 失败，运行报错
这个 PR 修复了 bug，把 0.29 的对应实现放在了一个新的文件里，增加可读性，并且准备以此为例子，对这部分代码进行重构。
另外对于装饰器函数，增加了 wrap(func) 的装饰。（原来的实现会改变函数 inspect 的内容，导致很难 debug）
> support diffusers v0.29

- .github/workflows/pub.yml
- onediff_diffusers_extensions/setup.py
- setup.py
VERSION_LOCAL_SCHEME=no-local-version python -m build
Successfully built onediff-1.1.1.dev66.tar.gz and onediff-1.1.1.dev66-py3-none-any.whl
> fix pub version
